# OpenArm Pico 4 Commanded EE Mode

arm_type: openarm
control_mode: follower_arms_forward_position_control
commanded_ee: true

arms:
  follower_l:
    can_interface_name: follower_l
    vr_controller: left
    torque_scaling: [0.9, 0.9, 0.8, 1.0, 0.8, 0.8, 0.8, 1.0]
    home_positions: [
      1.75, 0.0, 0.0, 1.0, 0.0, 0.0, -0.5, 0.0,
      2.5, 0.0, 0.0, 2.2, 0.0, 0.0, -0.75, 0.0,
      1.5, 0.0, 0.0, 2.2, 0.0, 0.0, -0.75, 0.0,
      0.0, -0.174, 0.0, 2.2, 0.0, 0.0, 0.0, 0.0,
      0.0, -0.174, 0.0, 1.5708, 0.0, 0.0, 0.0, 0.045]
    homing_kp: [20.0, 20.0, 20.0, 20.0, 5.0, 5.0, 5.0, 5.0]
    homing_kd: [2.75, 2.5, 0.7, 0.4, 0.7, 0.6, 0.5, 0.1]
    teleop_kp: [40.0, 40.0, 40.0, 40.0, 6.0, 7.0, 7.0, 0.1]
    teleop_kd: [3.0, 3.0, 3.0, 3.0, 0.2, 0.2, 0.2, 0.04]
    gripper_feedforward_torque: 0.8
    gripper_error_threshold: 0.003
  follower_r:
    can_interface_name: follower_r
    vr_controller: right
    torque_scaling: [0.9, 0.9, 0.8, 1.0, 0.8, 0.8, 0.8, 1.0]
    home_positions: [
      -1.75, 0.0, 0.0, 1.0, 0.0, 0.0, 0.5, 0.0,
      -2.5, 0.0, 0.0, 2.2, 0.0, 0.0, 0.75, 0.0,
      -1.5, 0.0, 0.0, 2.2, 0.0, 0.0, 0.75, 0.0,
      0.0, 0.174, 0.0, 2.2, 0.0, 0.0, 0.0, 0.0,
      0.0, 0.174, 0.0, 1.5708, 0.0, 0.0, 0.0, 0.045]
    homing_kp: [20.0, 20.0, 20.0, 20.0, 5.0, 5.0, 5.0, 5.0]
    homing_kd: [2.75, 2.5, 0.7, 0.4, 0.7, 0.6, 0.5, 0.1]
    teleop_kp: [40.0, 40.0, 40.0, 40.0, 6.0, 7.0, 7.0, 0.1]
    teleop_kd: [3.0, 3.0, 3.0, 3.0, 0.2, 0.2, 0.2, 0.04]
    gripper_feedforward_torque: 0.8
    gripper_error_threshold: 0.003
