# OpenYAM single left arm Pico 4 VR teleop

arm_type: openyam
control_mode: follower_arms_forward_position_control

arms:
  follower_l:
    can_interface_name: follower_l
    vr_controller: left
    torque_scaling: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    home_positions: [0.0, 0.873, 0.873, -0.698, 0.0, 0.0, 0.044]
    homing_kp: [10.0, 10.0, 10.0, 5.0, 5.0, 5.0, 5.0]
    homing_kd: [1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.1]
    teleop_kp: [60.0, 60.0, 60.0, 30.0, 12.0, 12.0, 0.1]
    teleop_kd: [2.0, 2.0, 2.0, 1.0, 0.2, 0.2, 0.04]
    gripper_feedforward_torque: 0.8
    gripper_error_threshold: 0.003
